### ISSUE TITLE
clothes didn't appear

### ISSUE THREAD

**Issue by chen3082** [pratikdhoriyani/Virtual-Dressing-Room#1]
Hey great project men.
However, while I was trying this project. After clicking "Try and Checkout", the clothes didn't appear. Could you enlighten me how to do so?

**Comment by pratikdhoriyani** [comment]
Thank You for appreciation...

* Please make sure that you have added cloths in CART using "Add To Cart" button.
* Then after adding cloths click on "Try & Checkout".

Here you will find all functionalities available to you :)

**Comment by pratikdhoriyani** [comment]
I hope you are now able to resolve this issue...
If you still having any queries then do not hesitate to write your query here...
Thank you so much for walk threw this :)
